### ISSUE TITLE
Using LDAP configuration in maximo

### ISSUE THREAD

**Issue by enriquemt** [ibm-maximo-dev/maximo-wotrack-polymer-sample#5]
I have LDAP configured in Maximo, so I do have to use Authorization header instead of maxauth.

Also I have read from the documentation that it is also necesary to concatenate 'Basic ' to the encoded64 user:password string.

I tried to change the maximo-login.html to:
maximoLoginAjax.headers['Authorization'] = 'Basic ' btoa(`${this.get('username')}:${this.get('password')}`)

However, I am unable to make it work.

**Comment by waxiamyer** [comment]
I tried you use this script no LDAP involved, just plain Maximo VMWare, but I'm getting "Error: Could not authenticate user" the script hitting maximo database, but it does not authenticate

Systemout Logs

`[3/27/22 17:52:21:541 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:21:541 [INFO] [MXServer] [CID-MXOSLC-48263] BMXAA6719I - USER = (MAXADMIN) SPID = (The database session identifier (spid) could not be retrieved for logging.) app (null) object (LOGINBLOCK) : select * from loginblock  where clientaddr =  '10.76.98.76.1'  and clienthost =  'DESKTOP-2EUSBDO'
[3/27/22 17:52:21:541 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:21:541 [INFO] [MXServer] [CID-MXOSLC-48263] BMXAA6719I - USER = (MAXADMIN) SPID = (The database session identifier
![Screenshot 2022-03-27 183650](https://user-images.githubusercontent.com/58050316/160306093-45e2c800-44ba-4a34-9d50-5af6a63ef412.png)
![Screenshot 2022-03-27 183650](https://user-images.githubusercontent.com/58050316/160306139-364f2b24-9b20-490d-affc-1de6e6206061.png)
 (spid) could not be retrieved for logging.) app (null) object (LOGINTRACKING) : select count(*) from logintracking  where attemptresult in ( 'FAILED' , 'FORGOTPSWD' ) and clientaddr =  '10.76.98.76.1'  and clienthost =  'DESKTOP-2EUSBDO'  and attemptdate >= (sysdate - (30/86400))
[3/27/22 17:52:21:554 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:21:554 [INFO] [MXServer] [CID-MXOSLC-48263] BMXAA6719I - USER = (MAXADMIN) SPID = (The database session identifier (spid) could not be retrieved for logging.) app (null) object (LOGINTRACKING) : insert into logintracking (currentcount,clienthost,userid,logintrackingid,attemptdate,serverhost,loginid,clientaddr,maxsessionuid,attemptresult,servername,name) values (?,?,?,?,?,?,?,?,?,?,?,?)
[3/27/22 17:52:21:554 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:21:554 [INFO] [MXServer] [CID-MXOSLC-48263] BMXAA6721I - Bind value for CURRENTCOUNT = 1
[3/27/22 17:52:21:554 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:21:554 [INFO] [MXServer] [CID-MXOSLC-48263] BMXAA6721I - Bind value for CLIENTHOST = DESKTOP-2EUSBDO
[3/27/22 17:52:21:554 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:21:554 [INFO] [MXServer] [CID-MXOSLC-48263] BMXAA6721I - Bind value for USERID = MXINTADM
[3/27/22 17:52:21:554 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:21:554 [INFO] [MXServer] [CID-MXOSLC-48263] BMXAA6721I - Bind value for LOGINTRACKINGID = 11094
[3/27/22 17:52:21:554 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:21:554 [INFO] [MXServer] [CID-MXOSLC-48263] BMXAA6721I - Bind value for ATTEMPTDATE = 2022-03-27 17:52:20.695
[3/27/22 17:52:21:554 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:21:554 [INFO] [MXServer] [CID-MXOSLC-48263] BMXAA6721I - Bind value for SERVERHOST = 10.76.98.76.132
[3/27/22 17:52:21:554 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:21:554 [INFO] [MXServer] [CID-MXOSLC-48263] BMXAA6721I - Bind value for LOGINID = mxintadm
[3/27/22 17:52:21:554 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:21:554 [INFO] [MXServer] [CID-MXOSLC-48263] BMXAA6721I - Bind value for CLIENTADDR = 10.76.98.76.1
[3/27/22 17:52:21:554 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:21:554 [INFO] [MXServer] [CID-MXOSLC-48263] BMXAA6721I - Bind value for MAXSESSIONUID = 7130
[3/27/22 17:52:21:554 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:21:554 [INFO] [MXServer] [CID-MXOSLC-48263] BMXAA6721I - Bind value for ATTEMPTRESULT = LOGIN
[3/27/22 17:52:21:554 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:21:554 [INFO] [MXServer] [CID-MXOSLC-48263] BMXAA6721I - Bind value for SERVERNAME = MXServer
[3/27/22 17:52:21:554 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:21:554 [INFO] [MXServer] [CID-MXOSLC-48263] BMXAA6721I - Bind value for NAME = MXINTADM
[3/27/22 17:52:22:132 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:22:132 [INFO] [MXServer] [CID-MXOSLC-48263] Correlated data: BEGIN LoginID:mxintadm RequestResourceSize:4 ClientIP:10.76.98.76.1 RequestURI:http://mx7vm/maximo/oslc/login SendResponseTime:0 ClientPort:61829 ElapsedTime:609 ms  END
[3/27/22 17:52:22:152 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:22:152 [INFO] [MXServer] [CID-MXOSLC-48264] Correlation started.
[3/27/22 17:52:22:152 CDT] 000000f2 SystemOut     O 27 Mar 2022 17:52:22:152 [ERROR] [MXServer] [CID-MXOSLC-48264] BMXAA0021E - User name and password combination are not valid. Try again.
psdi.util.MXSystemException: BMXAA0021E - User name and password combination are not valid. Try again.
	at com.ibm.tivoli.maximo.oslc.provider.MaximoAuthenticatorImpl.authenticateRequest(MaximoAuthenticatorImpl.java:212)
	at com.ibm.tivoli.maximo.oslc.provider.MaximoOslcProviderServlet.authenticateRequest(MaximoOslcProviderServlet.java:680)
	at com.ibm.tivoli.maximo.oslc.provider.MaximoOslcProviderServlet.doGet(MaximoOslcProviderServlet.java:460)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:575)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1232)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:781)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:480)
	at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:178)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:136)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:97)
	at psdi.webclient.system.filter.HttpXFrameOptionsFilter.doFilter(HttpXFrameOptionsFilter.java:38)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
	at psdi.webclient.system.filter.MTContextFilter.doFilter(MTContextFilter.java:53)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:967)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1107)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:3951)
	at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:304)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1015)
	at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:200)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:463)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:530)
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:316)
	at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88)
	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
	at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
	at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
	at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
	at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
	at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1892)`
@jamerson @stuckless @harikrishnagit
